### ISSUE TITLE
ERROR: compilation failed for package ‘git2r’ installation on Mac OS X 10.11.2

### ISSUE THREAD

**Issue by caijun** [ropensci/git2r#204]
In RStudio, I installed `git2r` package via

```
install.packages("git2r")
```

but the comilation failed.

```
In file included from libgit2/errors.c:8:
libgit2/global.h:22:11: fatal error: 'openssl/ssl.h' file not found
# include <openssl/ssl.h>
          ^
1 error generated.
make: *** [libgit2/errors.o] Error 1
ERROR: compilation failed for package ‘git2r’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/git2r’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/git2r’
```

My session information is as follows

```
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.2 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.2.3
```

**Comment by stewid** [comment]
Thanks for reporting the issue.

I'm working on improving the configuration.

**Comment by stewid** [comment]
I have made several changes to the configuration. Could you please try to install `git2r` from source using for example

```
git clone https://github.com/ropensci/git2r.git
R CMD INSTALL git2r
```

**Comment by mollihua** [comment]
I have tried your suggestion, but still failed to install git2r. Here is the output.

```{r}
* installing to library ‘/users/mochen/Library/R/3.2/library’
* installing *source* package ‘git2r’ ...
checking build system type... x86_64-apple-darwin15.0.0
checking host system type... x86_64-apple-darwin15.0.0
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for pkg-config... yes
checking for brew... yes
checking for library containing inflate... -lz
Homebrew requires Leopard or higher. For Tiger support, see:
http://github.com/sceaga/homebrew/tree/tiger
checking whether pkg-config could find libssh2... yes
checking for library containing iconv_open... no
configure: error: in `/private/var/folders/4t/8lclp7995n3bqcfj41xbfdm80000gn/T/RtmpW16h7M/downloaded_packages/git2r':
configure: error: iconv library required
See `config.log' for more details
ERROR: configuration failed for package ‘git2r’
* removing ‘/users/mochen/Library/R/3.2/library/git2r’
```

**Comment by caijun** [comment]
@stewid your suggestions works for me. Thank you very much.

**Comment by jennybc** [comment]
I am on OS 10.11.1 and got the same compilation error as @caijun, **when I install from github**.

Trying to install from 275416793ccca3f44e6d665bf7276b3c7d96b2f6, I got this:

```
In file included from libgit2/errors.c:8:
libgit2/global.h:22:11: fatal error: 'openssl/ssl.h' file not found
# include <openssl/ssl.h>
          ^
1 error generated.
make: *** [libgit2/errors.o] Error 1
ERROR: compilation failed for package ‘git2r’
* removing ‘/Users/jenny/resources/R/library/git2r’
* restoring previous ‘/Users/jenny/resources/R/library/git2r’
Error: Command failed (1)
```

So then I did `brew install openssl` and tried again with success (I think?). But I get lots of compilation warnings and also a notification that I will not have SSH support. I put everything I could capture in [this gist](https://gist.github.com/jennybc/28097c56e77074cca6a8#file-git2r-installation-txt) but this is truncated on the front end because it exceeds what RStudio Console stores.

**Comment by jennybc** [comment]
Update: the semi-success above is via `devtools::install_github("ropensci/git2r")`.

But `devtools::load_all()` fails and indeed `R CMD INSTALL git2r` still fails as before with the same message:

```
In file included from libgit2/errors.c:8:
libgit2/global.h:22:11: fatal error: 'openssl/ssl.h' file not found
# include <openssl/ssl.h>
          ^
1 error generated.
make: *** [libgit2/errors.o] Error 1
ERROR: compilation failed for package ‘git2r’
```

**Comment by stewid** [comment]
I have made several changes to the configuration. The error `libgit2/global.h:22:11: fatal error: 'openssl/ssl.h' file not found` should no longer happen. Instead, the missing OpenSSL library should be detected during the configuration with the following instruction how to install OpenSSL:

```
  ---------------------------------------------
   The OpenSSL library that is required to
   build git2r was not found.

   Please install:
     libssl-dev    (package on e.g. Debian and Ubuntu)
     openssl-devel (package on e.g. Fedora, CentOS and RHEL)
     openssl       (Homebrew package on OS X)
   and try again.

   If the OpenSSL library is installed on
   your system but the git2r configuration
   is unable to find it, you can specify
   the include and lib path to OpenSSL with:
   R CMD INSTALL --configure-args='--with-libssl-include=INCLUDE_PATH --with-libssl-lib=LIB_PATH' git2r
  ---------------------------------------------
```

I have successfully tested `devtools::load_all()`, `devtools::install_github('ropensci/git2r')` and `R CMD INSTALL git2r` on my system.

Could you please try to install the latest `git2r` on OS X.

**Comment by jennybc** [comment]
Yes I can do all of these successfully with 94f263d13a6b552a0128d1c10ed7a466d1b03032:

  * `devtools::install_github('ropensci/git2r')`
  * `devtools::load_all()`
  * `R CMD INSTALL git2r`

Still lots of compiler warnings but ... hey it works!

**Comment by stewid** [comment]
:smiley: That's very good news, indeed.

**Comment by mollihua** [comment]
I am also able to install git2r via terminal:
```{r}
brew install openssl
git clone https://github.com/ropensci/git2r.git
R CMD INSTALL git2r
```
Thank you!

**Comment by stewid** [comment]
@mollihua Thanks for testing

**Comment by Jemimacat** [comment]
@stewid Hi, Stewid. I meet the same problem. I'm on Centos 6 without root. And I have read this:

>   ---------------------------------------------
   The OpenSSL library that is required to
   build git2r was not found.

   Please install:
     libssl-dev    (package on e.g. Debian and Ubuntu)
     openssl-devel (package on e.g. Fedora, CentOS and RHEL)
     openssl       (Homebrew package on OS X)
   and try again.

   If the OpenSSL library is installed on
   your system but the git2r configuration
   is unable to find it, you can specify
   the include and lib path to OpenSSL with:
   R CMD INSTALL --configure-args='--with-libssl-include=INCLUDE_PATH --with-libssl-lib=LIB_PATH' git2r
  ---------------------------------------------

I try to install openssl and specify the INCLUDE_PATH and LIB_PATH, but still failed.

the Error Message is:

R CMD INSTALL --configure-args='--with-libssl-include=MY_DIR/mylib/openssl/include --with-libssl-lib=MY_DIR/openssl/lib' git2r
* installing to library 'MY_LIBRARY'
ERROR: cannot install to srcdir for package 'git2r'
* removing 'MY_LIBRARY/git2r'

How could I deal with this problem? Would you please to do me a favor? Thank you!

**Comment by Marc-Girondot** [comment]
Here is my solution to solve the same error in MacOSX Sierra 10.12.1 and R 3.3.2:
Install macport: https://www.macports.org

In terminal:

sudo port install wget
sudo port install openssl
wget https://cran.r-project.org/src/contrib/git2r_0.16.0.tar.gz
R CMD INSTALL --configure-args='--with-libssl-include=/opt/local/include --with-libssl-lib=/opt/local/lib' git2r_0.16.0.tar.gz
rm git2r_0.16.0.tar.gz

I have posted it here:
http://biostatsr.blogspot.fr/2016/11/install-git2r-from-source-on-macosx.html

**Comment by mremes** [comment]
With OS X 10.12.2 (Sierra), issue with  resolved with:
On cmd prompt (with Homebrew, use your package manager otherwise):
```
brew install wget
brew install openssl
```
In R CLI / RStudio
```
install.packages('git2r', type='mac.binary.mavericks')
```

**Comment by Jemimacat** [comment]
Thank you very much.

2017-01-03 21:31 GMT+08:00 Matti Remes <notifications@github.com>:

**Comment by swvanderlaan** [comment]
Hi,
I'm on macOS Sierra 10.12.5 and R 3.4.0. I've run: 

`brew install openssl`
`git clone https://github.com/ropensci/git2r.git`
`R CMD INSTALL git2r`

Everything works out fine at first, but in the end I still get an error. 

```
R CMD INSTALL git2r
* installing to library ‘/usr/local/lib/R/3.4/site-library’
* installing *source* package ‘git2r’ ...
checking build system type... x86_64-apple-darwin16.6.0
checking host system type... x86_64-apple-darwin16.6.0
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for brew... yes
checking how to run the C preprocessor... /usr/local/opt/llvm/bin/clang -fopenmp -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... no
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking size of void*... 0
configure: error: in `/Users/swvanderlaan/git/git2r':
configure: error: Unsupported architecture
See `config.log' for more details
ERROR: configuration failed for package ‘git2r’
* removing ‘/usr/local/lib/R/3.4/site-library/git2r’
```

What does that mean: `configure: error: Unsupported architecture`. Does it require an update for R or macOS?

Thanks for the help.

Sander

**Comment by LifeWorks** [comment]
I am having the same problem!

**Comment by milti** [comment]
yes, having the same error on macOS 13.3.3:

error for compilation is:

clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I. -Ilibgit2/src -Ilibgit2/include -Ilibgit2/deps/http-parser -I/usr/local/include -DGIT_ARCH_64 -I/usr/local/opt/openssl/include -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -DGIT_OPENSSL -DLIBGIT2_NO_FEATURES_H -DGIT_SHA1_COMMON_CRYPTO -DGIT_CURL -DGIT_USE_ICONV -DGIT_USE_STAT_MTIMESPEC -DGIT_USE_NSEC -DHAVE_FUTIMENS -DHAVE_QSORT_R   -I/usr/local/include  -Wno-deprecated-declarations  -fPIC  -Wall -g -O2  -c libgit2/src/fetch.c -o libgit2/src/fetch.o
In file included from libgit2/src/fetch.c:8:
In file included from libgit2/src/fetch.h:14:
libgit2/src/netops.h:16:11: fatal error: 'openssl/ssl.h' file not found
# include <openssl/ssl.h>
          ^~~~~~~~~~~~~~~
1 error generated.
make: *** [libgit2/src/fetch.o] Error 1
ERROR: compilation failed for package ‘git2r’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/git2r’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/git2r’
Installation failed: Command failed (1)
>

**Comment by tomschloss** [comment]
I'm using macOS 10.13.3

`brew install openssl` works for me. 

Perhaps this is the underlying issue (output from openssl install)?

`This formula is keg-only, which means it was not symlinked into /usr/local,
because Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries.`

**Comment by RafalLukawiecki** [comment]
Same issue

**Comment by RafalLukawiecki** [comment]
Further info on this issue on macOS 10.13.3. The above error only seems to affect me if openssl has been installed using macports. (Re)installing openssl using homebrew made the issue go away. I suppose it is a matter of the libraries not being in the expected paths, as per earlier comments.

**Comment by ezmiller** [comment]
Same issue

**Comment by devssh** [comment]
I had this problem, I am using homebrew only. Let me reinstall openssl and check if it is a factor.

**Comment by VVVFO** [comment]
After reading through the error messages it seems like the real cause of the issue is the absence of `libgit2`.  So the following worked for me:

```sh
# make sure you have openssl  as others suggested
brew install openssl
brew install libgit2
```

Then in RStudio:

```R
install.packages("git2r")
```
